# -*- coding: utf-8 -*-
"""ftp-client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198M9BgtZBrSEzOYwc0hBQHHuyGTOb7sy
"""

import socket

HOST = 'localhost'
PORT = 6666

while True:
    request = input()    
    sock = socket.socket()
    sock.connect((HOST, PORT))    
    sock.send(request.encode())    
    response = sock.recv(1024).decode()
    print(response)    
    sock.close()