# -*- coding: utf-8 -*-
"""my-FTP-client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198M9BgtZBrSEzOYwc0hBQHHuyGTOb7sy
"""

import socket
from authorization import auto

HOST = "localhost"
PORT = 50400
RECONNECTION_ENABLED = False

if __name__ == "__main__":
    is_started = False
    while RECONNECTION_ENABLED or not is_started:
        is_started = True
        print()
        print("Создать клиент")
        name = auto()
        if not name:
            continue
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.connect((HOST, PORT))
            print("Клиент подключен")
            data_bytes = name.encode()
            sock.send(data_bytes)
            while True:
                data = input("Введите сообщение для отправки:")
                if data == "exit":
                    print("Закрыто клиентом")
                    break
                data_bytes = data.encode()
                sock.send(data_bytes)
                data_bytes = sock.recv(1024)
                data = data_bytes.decode()
                print("Received:", repr(data))
                if not data:
                    print("Закрыто сервером")
                    break
            sock.close()
            print("Клиент отключен")