# -*- coding: utf-8 -*-
"""server_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198M9BgtZBrSEzOYwc0hBQHHuyGTOb7sy
"""

import unittest
import socket
from authorization import auto
from time import sleep

HOST = "localhost"
PORT = 50400
RECONNECTION_ENABLED = False

class Test1(unittest.TestCase):
    def test1(self):
        self.assertEqual(main("Test", ["makedir loop", "changedir loop", "createfile new1"]), ['makedir loop',"changedir loop" ,'createfile new1', 'Client disconnected'])
    def test2(self):
        self.assertEqual(main("Test", ["makedir loop", "changedir loop", "createfile new1"]), ['Incorrect directory name', 'changedir loop', 'Its file exists', 'Client disconnected'])        
    def test3(self):
        self.assertEqual(main("Test", ["changedir loop", "getpath", "createfile new3", "writefile new3 Hello!"]), ['changedir loop', '/home/odinmary/5_FTP_server/Test/loop', 'createfile new3', 'writefile new3 Hello!', 'Client disconnected'])

def main(name, acts):
    is_started = False
    report = []
    while RECONNECTION_ENABLED or not is_started:
        is_started = True
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.connect((HOST, PORT))
            sock.send(name.encode())
            print(name)
            sleep(1)
            for act in acts:
                if act == "exit":
                    report.append("Closed by client")
                    return report
                    break
                sock.send(act.encode())
                data = sock.recv(1024).decode()

                if not data:
                    report.append("Closed by server")
                    return report
                    break
                report.append(data)
            sock.close()
            report.append("Client disconnected")
            return report
            print(report)

if __name__ == "__main__":
    print(main("Test", ["makedir loop", "changedir loop", "createfile new1"]))
    # print(main("Test", ["makedir loop", "changedir loop", "createfile new1"]))
    # print(main("Test", ["changedir loop", "getpath", "createfile new3", "writefile new3 Hello!", "removefile new3"]))